#!/bin/sh

uci -q batch <<EOF
delete wireless.radio0.disabled
delete wireless.@wifi-iface[0]

set wireless.radio0.channel='5'
set wireless.radio0.htmode='HT20'
set wireless.radio0.country='DE'
set wireless.radio0.wmm='1'
set wireless.radio0.beacon_int='100'
set wireless.radio0.distance='50'
set wireless.radio0.basic_rate '6000 9000 12000 18000 24000 36000 48000 54000'

set wireless.wifi_freifunk='wifi-iface'
set wireless.wifi_freifunk.device='radio0'
set wireless.wifi_freifunk.network='freifunk'
set wireless.wifi_freifunk.mode='ap'
set wireless.wifi_freifunk.ssid_online='gel.freifunk.net'
set wireless.wifi_freifunk.ssid='Freifunk-Gerät startet...'

set wireless.wifi_mesh='wifi-iface'
set wireless.wifi_mesh.device='radio0'
set wireless.wifi_mesh.network='mesh'
set wireless.wifi_mesh.mode='adhoc'

set wireless.wifi_mesh.ssid='FF-BATBONE v14'
set wireless.wifi_mesh.bssid='02:CA:FF:EE:21:96'
set wireless.wifi_mesh.mcast_rate='1000'

commit wireless
EOF
